# fly.toml app configuration file generated for deerpark-api on 2026-04-24T09:37:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deerpark-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  HEADLINE_INGEST_INTERVAL_MIN = '15'
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
